runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wsgi:app --timeout 900

runtime_config:
    python_version: 3

env_variables:
    DB_CONNECTION_STRING: postgresql://postgresUser:[password]:@10.78.160.3:5432/[bdName]

resources:
  cpu: 2
  memory_gb: 2.0
  disk_size_gb: 10